from django.conf import settings
from django.db import models


class Alert(models.Model):
    """
    Stores health alerts generated by rule-based checks or (future) AI models.

    Each alert is linked to the user and optionally to the health record
    that triggered it, enabling traceability.
    """

    # ── Alert Types ─────────────────────────────────
    TYPE_CHOICES = [
        ('high_heart_rate', 'High Heart Rate'),
        ('low_heart_rate', 'Low Heart Rate'),
        ('low_spo2', 'Low Blood Oxygen'),
        ('poor_sleep', 'Poor Sleep'),
        ('high_bp', 'High Blood Pressure'),
        ('low_bp', 'Low Blood Pressure'),
        ('high_temperature', 'High Temperature'),
        ('custom', 'Custom Alert'),
    ]

    # ── Severity Levels ─────────────────────────────
    SEVERITY_CHOICES = [
        ('info', 'Informational'),
        ('warning', 'Warning'),
        ('critical', 'Critical'),
    ]

    # ── Source (for future AI upgrade) ──────────────
    SOURCE_CHOICES = [
        ('rule_engine', 'Rule Engine'),
        ('ai_model', 'AI Model'),
        ('manual', 'Manual'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='alerts',
        db_index=True,
    )
    health_record = models.ForeignKey(
        'health_data.HealthData',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='triggered_alerts',
        help_text="The health record that triggered this alert",
    )

    # ── Alert Details ───────────────────────────────
    alert_type = models.CharField(max_length=30, choices=TYPE_CHOICES, db_index=True)
    severity = models.CharField(max_length=10, choices=SEVERITY_CHOICES, default='warning')
    title = models.CharField(max_length=200)
    message = models.TextField()
    metric_value = models.CharField(
        max_length=50, blank=True, default='',
        help_text="The actual value that triggered the alert (e.g., '112 bpm')",
    )
    threshold = models.CharField(
        max_length=50, blank=True, default='',
        help_text="The threshold that was exceeded (e.g., '> 100 bpm')",
    )
    source = models.CharField(max_length=20, choices=SOURCE_CHOICES, default='rule_engine')

    # ── Status ──────────────────────────────────────
    is_read = models.BooleanField(default=False, db_index=True)
    is_dismissed = models.BooleanField(default=False)

    # ── Timestamps ──────────────────────────────────
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    read_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'alerts'
        ordering = ['-created_at']
        verbose_name = 'Health Alert'
        verbose_name_plural = 'Health Alerts'
        indexes = [
            models.Index(fields=['user', '-created_at'], name='idx_user_alert_date'),
            models.Index(fields=['user', 'is_read'], name='idx_user_alert_read'),
        ]

    def __str__(self):
        return f"[{self.severity.upper()}] {self.title} — {self.user.username}"
