# Generated by Django 6.0.4 on 2026-04-08 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_heart_rate', 'High Heart Rate'), ('low_heart_rate', 'Low Heart Rate'), ('low_spo2', 'Low Blood Oxygen'), ('poor_sleep', 'Poor Sleep'), ('high_bp', 'High Blood Pressure'), ('low_bp', 'Low Blood Pressure'), ('high_temperature', 'High Temperature'), ('custom', 'Custom Alert')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('metric_value', models.CharField(blank=True, default='', help_text="The actual value that triggered the alert (e.g., '112 bpm')", max_length=50)),
                ('threshold', models.CharField(blank=True, default='', help_text="The threshold that was exceeded (e.g., '> 100 bpm')", max_length=50)),
                ('source', models.CharField(choices=[('rule_engine', 'Rule Engine'), ('ai_model', 'AI Model'), ('manual', 'Manual')], default='rule_engine', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('health_record', models.ForeignKey(blank=True, help_text='The health record that triggered this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='health_data.healthdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Alert',
                'verbose_name_plural': 'Health Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_user_alert_date'), models.Index(fields=['user', 'is_read'], name='idx_user_alert_read')],
            },
        ),
    ]
