# Generated by Django 6.0.4 on 2026-04-07 21:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Heart rate in bpm (30–250)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
                ('spo2', models.DecimalField(blank=True, decimal_places=1, help_text='Blood oxygen saturation % (50–100)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('steps', models.PositiveIntegerField(blank=True, help_text='Step count for the period', null=True)),
                ('calories_burned', models.DecimalField(blank=True, decimal_places=1, help_text='Calories burned (kcal)', max_digits=7, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total sleep in hours (0–24)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('systolic_bp', models.PositiveIntegerField(blank=True, help_text='Systolic blood pressure (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(250)])),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, help_text='Diastolic blood pressure (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)])),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in °C', max_digits=4, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('fitbit', 'Fitbit'), ('apple_watch', 'Apple Watch'), ('garmin', 'Garmin'), ('samsung', 'Samsung Health'), ('other', 'Other Device')], default='manual', help_text='Data source / wearable device', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the reading was taken')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'db_table': 'health_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='idx_user_timestamp')],
            },
        ),
    ]
