# Generated by Django 6.0.4 on 2026-04-08 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='When the access token expires')),
                ('fitbit_user_id', models.CharField(blank=True, default='', help_text='Fitbit user ID returned during auth', max_length=50)),
                ('scope', models.TextField(blank=True, default='', help_text='Granted OAuth scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitbit_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fitbit Token',
                'verbose_name_plural': 'Fitbit Tokens',
                'db_table': 'fitbit_tokens',
            },
        ),
    ]
